name: "easy-stay"
version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_LOCAL_PORT}:${DB_DOCKER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -P ${DB_DOCKER_PORT} -u ${DB_USERNAME} -p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    image: easy-stay
    build: .
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url": "jdbc:mysql://mysqldb:${DB_DOCKER_PORT}/${DB_NAME}?serverTimezone=UTC", 
      "spring.datasource.username": "${DB_USERNAME}", 
      "spring.datasource.password": "${DB_PASSWORD}",
      "stripe.api.key": "${STRIPE_API_KEY}",
      "telegram.bot.token": "${BOT_TOKEN}",
      "telegram.bot.username": "${BOT_USERNAME}",
      "jwt.secret": "${JWT_SECRET}",
      "app.base.url": "${BASE_URL}"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
